version: '3.5'

services:
    redis:
      image: redis
      ports:
        - 6379:6379  
      networks:
        - redis 
    backend:
      image: backend-example-docker
      ports:
        - 8000:8000
      volumes:
        - ./logs.txt:/logs.txt
      container_name: backend-example-2.5
      environment:
        - REDIS=redis
      networks:
        - redis

    frontend:
      image: frontend-example-docker
      ports:
        - 5000:5000
      container_name: frontend-example-2.5

networks:
    redis:
      name: redis
