version: '3.5'

services:
    backend:
      image: backend-example-docker
      ports:
        - 8000:8000
      volumes:
        - ./logs.txt:/logs.txt
      container_name: backend-example
 
    frontend:
      image: frontend-example-docker
      ports:
        - 5000:5000
      container_name: frontend-example

